COIN = 'COIN'
TOOL_WOODEN_PICKAXE = 'TOOL_WOODEN_PICKAXE'
MATERIAL_WOOD = 'MATERIAL_WOOD'

SOURCE_RECIPES = './data/recipes.pkl'
SOURCE_MINES = './data/mines.pkl'
SOURCE_TOOLS = './data/tools.pkl'
SOURCE_MATERIALS = './data/materials.pkl'
SOURCE_I18N = './data/i18n.pkl'
SOURCE_PLAYER = './data/player.pkl'
SOURCE_FOOD = './data/food.pkl'
SOURCE_UTILITY = './data/utility.pkl'
